PART1_TOPICS = [
    "a famous explorer or journey",
    "underwater life and the ocean",
    "a local festival or tradition",
    "inventing something by accident",
    "migration of birds or animals",
    "a childhood memory of a place",
    "street art and urban culture",
    "how coffee or tea became popular",
    "a lost and found object",
    "the history of a bridge or building",
    "volunteering in a community project",
    "learning to cook a family recipe",
    "a day in the life of a lighthouse keeper",
    "the origin of a superstition",
    "a musician's first concert",
    "repairing an old vehicle or machine",
    "a scientific experiment at school",
    "moving to a new country",
    "a surprise party or celebration",
    "wildlife in cities",
    "an unusual hobby or collection",
    "a long-distance friendship",
    "the discovery of a hidden garden",
    "a sports team's comeback",
    "how a word or phrase entered the language",
    "a journey by boat or train",
    "a chef's visit to a market",
    "the first day at a new job",
    "a mystery or detective story",
    "climate and weather in a region",
    "a museum or gallery visit",
    "learning to ride a bike or drive",
    "a famous invention and its impact",
    "life in a remote village",
    "a pet that changed someone's life",
    "the story behind a painting or sculpture",
    "a camping or hiking adventure",
    "how newspapers were first delivered",
    "a talent show or competition",
    "the history of a sport",
    "a rescue or act of bravery",
    "food from different cultures",
    "a photographer's favourite subject",
    "ancient customs that still exist",
    "noise and silence in modern life",
    "a journey to the mountains",
    "how a town got its name",
    "a surprise encounter with a celebrity",
    "the importance of sleep",
    "a craft or skill passed down generations",
    "a shipwreck or lost treasure",
    "the life of a street performer",
    "how people celebrated before the internet",
    "a doctor or nurse's memorable day",
    "the history of a park or square",
    "a misunderstanding that led to friendship",
    "extreme weather or natural event",
    "a book that changed someone's view",
    "life on a farm or in the countryside",
    "the first aeroplane flight",
    "a teacher who made a difference",
    "the story of a famous landmark",
    "nocturnal animals and night life",
    "a family business that grew",
    "how music affects mood",
    "a journey through a desert",
    "the tradition of sending postcards",
    "a scientist's breakthrough",
    "sharing a flat or house with others",
    "the history of a type of dance",
    "a film that became a classic",
    "living without technology for a week",
    "a firefighter's or paramedic's story",
    "how languages borrow words",
    "a boat race or sailing event",
    "the meaning of dreams",
    "a comedian's first performance",
    "life in a treehouse or unusual home",
    "the invention of the bicycle",
    "a reunion after many years",
    "endangered species and conservation",
    "a journalist's most memorable interview",
    "the origin of a holiday",
    "learning a new language abroad",
    "a circus or carnival",
    "the story of a famous painting",
    "noise pollution in cities",
    "a pilot's first solo flight",
    "how chocolate is made",
    "a neighbour who became a friend",
    "the history of a river or canal",
    "a magician's secret",
    "life without electricity",
    "the first heart transplant",
    "a gardener's favourite season",
    "the tradition of afternoon tea",
    "a runner's first marathon",
    "how cartoons are made",
    "a sailor's voyage",
    "the discovery of a new species",
    "a baker's early morning",
    "the history of the postal service",
    "a surprise gift or gesture",
    "life in the Arctic or Antarctic",
    "the story of a famous song",
    "queueing and waiting in different cultures",
    "a vet's most unusual patient",
    "how the calendar was invented",
    "a dancer's audition",
    "the tradition of birthday cakes",
    "a cyclist's long-distance ride",
    "how soap was first made",
    "a librarian's favourite book",
    "the history of a castle",
    "a comedian's worst gig",
    "life on board a spaceship",
    "the invention of the telephone",
    "a surprise visit from a relative",
    "coral reefs and marine life",
    "the story of a famous photograph",
    "silence in meditation and mindfulness",
    "an architect's dream project",
    "how fireworks were invented",
    "a farmer's harvest day",
    "the tradition of shaking hands",
    "a climber's near miss",
    "how ice cream spread around the world",
    "a nurse's night shift",
    "the history of a theatre",
    "a writer's block and how they overcame it",
    "life in a monastery or convent",
    "the invention of the camera",
    "a surprise proposal",
    "bees and pollination",
    "the story behind a monument",
    "laughter and humour across cultures",
    "an astronaut's training",
    "how the weekend was created",
    "a fisherman's biggest catch",
    "the tradition of toasting",
    "a surfer's perfect wave",
    "how paper was first made",
    "a bus driver's route",
    "the history of a university",
    "a musician's worst performance",
    "life in a tent or caravan",
    "the invention of the umbrella",
    "a surprise inheritance",
    "owls and other night birds",
    "the story of a famous statue",
    "gestures and body language worldwide",
    "a diver's discovery",
    "how the alphabet was formed",
    "a barber's or hairdresser's tale",
    "the tradition of wedding rings",
    "a skier's avalanche escape",
    "how tea reached Europe",
    "a taxi driver's passenger",
    "the history of a stadium",
    "a painter's favourite light",
    "life in a yurt or igloo",
    "the invention of the wheel",
    "a surprise reunion at an airport",
    "bats and echolocation",
    "the story of a famous bridge",
    "punctuality in different countries",
    "a sailor's storm at sea",
    "how the first map was drawn",
    "a florist's busiest day",
    "the tradition of blowing out candles",
    "a mountaineer's summit",
    "how spices changed history",
    "a train conductor's story",
    "the history of a library",
    "a sculptor's block of stone",
    "life in a submarine",
    "the invention of the mirror",
    "a surprise letter from the past",
    "ants and colony behaviour",
    "the story of a famous tower",
    "siesta and rest around the world",
    "a pilot's emergency landing",
    "how the first book was printed",
    "a jeweller's most valuable piece",
    "the tradition of exchanging gifts",
    "a sailor's round-the-world trip",
    "how sugar spread across the world",
    "a busker's best day",
    "the history of a hospital",
    "a potter's kiln disaster",
    "life in a cave or underground",
    "the invention of the compass",
    "a surprise guest at a wedding",
    "dolphins and communication",
    "the story of a famous fountain",
    "hospitality in different cultures",
    "a cyclist's accident and recovery",
    "how the first clock was made",
    "a tailor's perfect suit",
    "the tradition of naming ships",
    "a kayaker's river journey",
    "how tomatoes came to Europe",
    "a street cleaner's morning",
    "the history of a prison",
    "a glassblower's technique",
    "life in a tree",
    "the invention of the lock",
    "a surprise discovery in an attic",
    "wolves and pack behaviour",
    "the story of a famous square",
    "table manners across cultures",
    "a balloonist's flight",
    "how the first lens was made",
    "a blacksmith's forge",
    "the tradition of midnight on New Year",
    "a rower's race",
    "how potatoes changed diets",
    "a night watchman's rounds",
    "the history of a cemetery",
    "a weaver's pattern",
    "life on a desert island",
    "the invention of the needle",
    "a surprise message in a bottle",
    "elephants and memory",
    "the story of a famous gate",
    "greetings around the world",
]

PART3_TOPICS = [
    "a famous explorer or journey",
    "underwater life and the ocean",
    "a local festival or tradition",
    "migration of birds or animals",
    "street art and urban culture",
    "how coffee or tea became popular",
    "a lost and found object",
    "the history of a bridge or building",
    "volunteering in a community project",
    "learning to cook a family recipe",
    "a day in the life of a lighthouse keeper",
    "the origin of a superstition",
    "a musician's first concert",
    "repairing an old vehicle or machine",
    "a scientific experiment at school",
    "moving to a new country",
    "a surprise party or celebration",
    "wildlife in cities",
    "an unusual hobby or collection",
    "a long-distance friendship",
    "the discovery of a hidden garden",
    "a sports team's comeback",
    "how a word entered the language",
    "a journey by boat or train",
    "a chef's visit to a market",
    "the first day at a new job",
    "a mystery or detective story",
    "climate and weather in a region",
    "a museum or gallery visit",
    "learning to ride a bike or drive",
    "a famous invention and its impact",
    "life in a remote village",
    "a pet that changed someone's life",
    "the story behind a painting or sculpture",
    "a camping or hiking adventure",
    "how newspapers were first delivered",
    "a talent show or competition",
    "the history of a sport",
    "a rescue or act of bravery",
    "food from different cultures",
    "a photographer's favourite subject",
    "ancient customs that still exist",
    "noise and silence in modern life",
    "a journey to the mountains",
    "how a town got its name",
    "a surprise encounter with a celebrity",
    "the importance of sleep",
    "a craft or skill passed down generations",
    "a shipwreck or lost treasure",
    "the life of a street performer",
    "how people celebrated before the internet",
    "a doctor or nurse's memorable day",
    "the history of a park or square",
    "a misunderstanding that led to friendship",
    "extreme weather or natural event",
    "a book that changed someone's view",
    "life on a farm or in the countryside",
    "the first aeroplane flight",
    "a teacher who made a difference",
    "the story of a famous landmark",
    "nocturnal animals and night life",
    "a family business that grew",
    "how music affects mood",
    "a journey through a desert",
    "the tradition of sending postcards",
    "a scientist's breakthrough",
    "sharing a flat or house with others",
    "the history of a type of dance",
    "a film that became a classic",
    "living without technology for a week",
    "a firefighter's or paramedic's story",
    "how languages borrow words",
    "a boat race or sailing event",
    "the meaning of dreams",
    "a comedian's first performance",
    "life in a treehouse or unusual home",
    "the invention of the bicycle",
    "a reunion after many years",
    "endangered species and conservation",
    "a journalist's most memorable interview",
    "the origin of a holiday",
    "learning a new language abroad",
    "a circus or carnival",
    "the story of a famous painting",
    "noise pollution in cities",
    "a pilot's first solo flight",
    "how chocolate is made",
    "a neighbour who became a friend",
    "the history of a river or canal",
    "a magician's secret",
    "life without electricity",
    "the first heart transplant",
    "a gardener's favourite season",
    "the tradition of afternoon tea",
    "a runner's first marathon",
    "how cartoons are made",
    "a sailor's voyage",
    "the discovery of a new species",
    "a baker's early morning",
    "the history of the postal service",
    "a surprise gift or gesture",
    "life in the Arctic or Antarctic",
    "the story of a famous song",
    "queueing and waiting in different cultures",
    "a vet's most unusual patient",
    "how the calendar was invented",
    "a dancer's audition",
    "the tradition of birthday cakes",
    "a cyclist's long-distance ride",
    "how soap was first made",
    "a librarian's favourite book",
    "the history of a castle",
    "a comedian's worst gig",
    "life on board a spaceship",
    "the invention of the telephone",
    "a surprise visit from a relative",
    "coral reefs and marine life",
    "the story of a famous photograph",
    "silence in meditation and mindfulness",
    "an architect's dream project",
    "how fireworks were invented",
    "a farmer's harvest day",
    "the tradition of shaking hands",
    "a climber's near miss",
    "how ice cream spread around the world",
    "a nurse's night shift",
    "the history of a theatre",
    "a writer's block and how they overcame it",
    "life in a monastery or convent",
    "the invention of the camera",
    "a surprise proposal",
    "bees and pollination",
    "the story behind a monument",
    "laughter and humour across cultures",
    "an astronaut's training",
    "how the weekend was created",
    "a fisherman's biggest catch",
    "the tradition of toasting",
    "a surfer's perfect wave",
    "how paper was first made",
    "a bus driver's route",
    "the history of a university",
    "a musician's worst performance",
    "life in a tent or caravan",
    "the invention of the umbrella",
    "a surprise inheritance",
    "owls and other night birds",
    "the story of a famous statue",
    "gestures and body language worldwide",
    "a diver's discovery",
    "how the alphabet was formed",
    "a barber's or hairdresser's tale",
    "the tradition of wedding rings",
    "a skier's avalanche escape",
    "how tea reached Europe",
    "a taxi driver's passenger",
    "the history of a stadium",
    "a painter's favourite light",
    "life in a yurt or igloo",
    "the invention of the wheel",
    "a surprise reunion at an airport",
    "bats and echolocation",
    "the story of a famous bridge",
    "punctuality in different countries",
    "a sailor's storm at sea",
    "how the first map was drawn",
    "a florist's busiest day",
    "the tradition of blowing out candles",
    "a mountaineer's summit",
    "how spices changed history",
    "a train conductor's story",
    "the history of a library",
    "a sculptor's block of stone",
    "life in a submarine",
    "the invention of the mirror",
    "a surprise letter from the past",
    "ants and colony behaviour",
    "the story of a famous tower",
    "siesta and rest around the world",
    "a pilot's emergency landing",
    "how the first book was printed",
    "a jeweller's most valuable piece",
    "the tradition of exchanging gifts",
    "a sailor's round-the-world trip",
    "how sugar spread across the world",
    "a busker's best day",
    "the history of a hospital",
    "a potter's kiln disaster",
    "life in a cave or underground",
    "the invention of the compass",
    "a surprise guest at a wedding",
    "dolphins and communication",
    "the story of a famous fountain",
    "hospitality in different cultures",
    "a cyclist's accident and recovery",
    "how the first clock was made",
    "a tailor's perfect suit",
    "the tradition of naming ships",
    "a kayaker's river journey",
    "how tomatoes came to Europe",
    "a street cleaner's morning",
    "the history of a prison",
    "a glassblower's technique",
    "life in a tree",
    "the invention of the lock",
    "a surprise discovery in an attic",
    "wolves and pack behaviour",
    "the story of a famous square",
    "table manners across cultures",
    "a balloonist's flight",
    "how the first lens was made",
    "a blacksmith's forge",
    "the tradition of midnight on New Year",
    "a rower's race",
    "how potatoes changed diets",
    "a night watchman's rounds",
    "the history of a cemetery",
    "a weaver's pattern",
    "life on a desert island",
    "the invention of the needle",
    "a surprise message in a bottle",
    "elephants and memory",
    "the story of a famous gate",
    "greetings around the world",
]
PART5_TOPICS = [
    "the psychology of decision-making",
    "how social media has changed journalism",
    "the rise and fall of a once-popular technology",
    "why people collect things",
    "the hidden cost of fast fashion",
    "how architecture shapes our behaviour",
    "the science behind first impressions",
    "urban farming and the future of food",
    "the influence of music on productivity",
    "why some languages disappear",
    "the ethics of artificial intelligence",
    "how childhood play affects adult creativity",
    "the impact of tourism on small communities",
    "the psychology of colour in marketing",
    "why we procrastinate and how to stop",
    "the role of storytelling in human culture",
    "how sleep deprivation affects society",
    "the debate around screen time for children",
    "the rediscovery of ancient farming techniques",
    "how volunteering changes the volunteer",
    "the economics of happiness",
    "why some innovations take decades to adopt",
    "the relationship between exercise and mental health",
    "how translated literature broadens our worldview",
    "the unexpected effects of remote work on cities",
    "why nostalgia is a powerful emotion",
    "the future of public libraries",
    "how wildlife corridors help endangered species",
    "the role of failure in scientific discovery",
    "the changing meaning of luxury",
    "how online reviews shape consumer behaviour",
    "the problem with food waste in developed countries",
    "the appeal of minimalist living",
    "how museums are reinventing themselves",
    "the link between nature and wellbeing",
    "why handwriting still matters in a digital age",
    "the impact of megacities on the environment",
    "how music therapy is used in hospitals",
    "the rise of citizen science",
    "why we are drawn to conspiracy theories",
    "the history and future of space exploration",
    "how bilingualism affects the brain",
    "the challenges of preserving cultural heritage",
    "why some diets become global trends",
    "the role of humour in education",
    "how driverless cars could reshape cities",
    "the hidden world of underground rivers",
    "why people fear public speaking",
    "the changing role of grandparents in modern families",
    "how coral reef restoration is progressing",
    "the psychology of waiting in queues",
    "why craft beer became a global movement",
    "the impact of light pollution on wildlife",
    "how coworking spaces are changing business culture",
    "the tradition of long-distance hiking trails",
    "why people move abroad and what they learn",
    "the science of memory and forgetting",
    "how street food became fine dining",
    "the effect of climate change on winter sports",
    "why we anthropomorphise animals",
    "the evolution of the modern workplace",
    "how podcasts changed storytelling",
    "the debate over zoos and animal welfare",
    "why some cities are banning cars from centres",
    "the role of mentors in career success",
    "how ocean currents affect global weather",
    "the surprising benefits of boredom",
    "why secondhand shopping is booming",
    "the relationship between art and politics",
    "how community gardens transform neighbourhoods",
    "the science behind optical illusions",
    "why traditional markets are making a comeback",
    "the impact of robotics on everyday life",
    "how adventure tourism is evolving",
    "the psychology of brand loyalty",
    "why certain accents are perceived differently",
    "the history of public transport in major cities",
    "how renewable energy is reshaping economies",
    "the role of trust in online communities",
    "why some people thrive under pressure",
    "the future of personalised medicine",
    "how documentary films influence public opinion",
    "the hidden costs of convenience culture",
    "why learning a musical instrument benefits adults",
    "the impact of deforestation on local climate",
    "how escape rooms became a global phenomenon",
    "the changing attitudes to work-life balance",
    "why emotional intelligence matters at work",
    "the science of taste and flavour",
    "how citizen journalism is reshaping news",
    "the role of parks in urban mental health",
    "why tiny houses appeal to a growing audience",
    "the effect of globalisation on local cuisines",
    "how theatre adapts to modern audiences",
    "the psychology of gift-giving",
    "why rewilding projects are gaining support",
    "the future of sustainable fashion",
    "how augmented reality is used in education",
    "the tradition of oral history in different cultures",
    "why introverts and extroverts work differently",
]

PART6_TOPICS = [
    "the revival of vinyl records in the streaming age",
    "how vertical gardens are changing city skylines",
    "the science behind animal migration patterns",
    "why storytelling is essential in business",
    "the impact of microplastics on marine ecosystems",
    "how night shifts affect long-term health",
    "the growing popularity of board games among adults",
    "why some ancient buildings survived centuries",
    "the role of sign language in inclusive education",
    "how forest bathing became a wellness trend",
    "the economics of the gig economy",
    "why colour-blind design matters in technology",
    "the history of the concept of zero",
    "how community radio stations serve remote areas",
    "the debate over homework in primary schools",
    "why certain songs get stuck in our heads",
    "the effect of altitude on athletic performance",
    "how food labels influence what we buy",
    "the tradition of apprenticeships in skilled trades",
    "why dark tourism is a growing travel niche",
    "the science of soil and why it matters",
    "how co-housing communities are designed",
    "the impact of noise on concentration and learning",
    "why some inventions were ahead of their time",
    "the role of photography in conservation",
    "how floating cities could address rising sea levels",
    "the psychology of habit formation",
    "why fermented foods are back in fashion",
    "the hidden history of women in science",
    "how bike-sharing schemes reduce urban congestion",
    "the growing field of forensic linguistics",
    "why people are drawn to extreme sports",
    "the art of restoring old buildings",
    "how satellite technology monitors deforestation",
    "the role of laughter in social bonding",
    "why slow travel is gaining followers",
    "the science behind earthquake-proof architecture",
    "how language shapes our perception of time",
    "the impact of fast internet on rural communities",
    "why traditional crafts are valued in modern design",
    "the debate about universal basic income",
    "how urban beekeeping supports local ecosystems",
    "the psychology behind fear of missing out",
    "why some rivers are being granted legal rights",
    "the evolution of children's playgrounds",
    "how therapeutic gardening helps mental health",
    "the influence of weather on mood and behaviour",
    "why fountain pen enthusiasts are growing in number",
    "the role of libraries in digital literacy",
    "how 3D printing is transforming prosthetics",
    "the tradition of communal meals across cultures",
    "why light therapy works for seasonal disorders",
    "the science of acoustics in concert hall design",
    "how fair-trade certification changed global farming",
    "the impact of artificial lighting on sleep patterns",
    "why walking meetings improve creativity",
    "the history of botanical gardens",
    "how crowdfunding is reshaping product development",
    "the psychology of colour in interior design",
    "why bird-watching has become mainstream",
    "the role of interpreters in international diplomacy",
    "how community fridges tackle food waste",
    "the debate over daylight saving time",
    "why some cultures value silence in conversation",
    "the science of preserving ancient manuscripts",
    "how electric ferries are reducing harbour pollution",
    "the impact of social isolation on elderly people",
    "why origami principles are used in engineering",
    "the growing movement to protect dark skies",
    "how seed banks safeguard biodiversity",
    "the tradition of public bathhouses around the world",
    "why people are choosing to learn dead languages",
    "the role of drones in wildlife conservation",
    "how pop-up shops are changing retail",
    "the psychology of superstition in sport",
    "why bamboo is called the material of the future",
    "the science behind desalination technology",
    "how storytelling robots are used in elder care",
    "the impact of volcanic eruptions on global climate",
    "why repair cafes are spreading across Europe",
    "the evolution of public swimming pools",
    "how algae could become a major food source",
    "the role of colour in animal camouflage",
    "why underground architecture is gaining interest",
    "the debate over genetically modified crops",
    "how assistive technology empowers disabled athletes",
    "the tradition of stone walls and dry-stone building",
    "why tree-planting campaigns sometimes fail",
    "the science of composting and soil regeneration",
    "how lighthouse keepers' lives changed with automation",
    "the impact of cultural festivals on local economies",
    "why people collect rare books",
    "the role of cartography in exploration history",
    "how soundscapes are used in urban planning",
    "the growing appeal of train travel over flying",
    "why knitting circles are popular among young adults",
    "the science behind bioluminescence in the ocean",
    "how guerrilla gardening reclaims urban spaces",
    "the psychology of choosing where to sit in a room",
    "why edible insects are considered food of the future",
    "the evolution of weather forecasting technology",
]
