PART1_TOPICS = [
    "a famous explorer or journey",
    "underwater life and the ocean",
    "a local festival or tradition",
    "inventing something by accident",
    "migration of birds or animals",
    "a childhood memory of a place",
    "street art and urban culture",
    "how coffee or tea became popular",
    "a lost and found object",
    "the history of a bridge or building",
    "volunteering in a community project",
    "learning to cook a family recipe",
    "a day in the life of a lighthouse keeper",
    "the origin of a superstition",
    "a musician's first concert",
    "repairing an old vehicle or machine",
    "a scientific experiment at school",
    "moving to a new country",
    "a surprise party or celebration",
    "wildlife in cities",
    "an unusual hobby or collection",
    "a long-distance friendship",
    "the discovery of a hidden garden",
    "a sports team's comeback",
    "how a word or phrase entered the language",
    "a journey by boat or train",
    "a chef's visit to a market",
    "the first day at a new job",
    "a mystery or detective story",
    "climate and weather in a region",
    "a museum or gallery visit",
    "learning to ride a bike or drive",
    "a famous invention and its impact",
    "life in a remote village",
    "a pet that changed someone's life",
    "the story behind a painting or sculpture",
    "a camping or hiking adventure",
    "how newspapers were first delivered",
    "a talent show or competition",
    "the history of a sport",
    "a rescue or act of bravery",
    "food from different cultures",
    "a photographer's favourite subject",
    "ancient customs that still exist",
    "noise and silence in modern life",
    "a journey to the mountains",
    "how a town got its name",
    "a surprise encounter with a celebrity",
    "the importance of sleep",
    "a craft or skill passed down generations",
    "a shipwreck or lost treasure",
    "the life of a street performer",
    "how people celebrated before the internet",
    "a doctor or nurse's memorable day",
    "the history of a park or square",
    "a misunderstanding that led to friendship",
    "extreme weather or natural event",
    "a book that changed someone's view",
    "life on a farm or in the countryside",
    "the first aeroplane flight",
    "a teacher who made a difference",
    "the story of a famous landmark",
    "nocturnal animals and night life",
    "a family business that grew",
    "how music affects mood",
    "a journey through a desert",
    "the tradition of sending postcards",
    "a scientist's breakthrough",
    "sharing a flat or house with others",
    "the history of a type of dance",
    "a film that became a classic",
    "living without technology for a week",
    "a firefighter's or paramedic's story",
    "how languages borrow words",
    "a boat race or sailing event",
    "the meaning of dreams",
    "a comedian's first performance",
    "life in a treehouse or unusual home",
    "the invention of the bicycle",
    "a reunion after many years",
    "endangered species and conservation",
    "a journalist's most memorable interview",
    "the origin of a holiday",
    "learning a new language abroad",
    "a circus or carnival",
    "the story of a famous painting",
    "noise pollution in cities",
    "a pilot's first solo flight",
    "how chocolate is made",
    "a neighbour who became a friend",
    "the history of a river or canal",
    "a magician's secret",
    "life without electricity",
    "the first heart transplant",
    "a gardener's favourite season",
    "the tradition of afternoon tea",
    "a runner's first marathon",
    "how cartoons are made",
    "a sailor's voyage",
    "the discovery of a new species",
    "a baker's early morning",
    "the history of the postal service",
    "a surprise gift or gesture",
    "life in the Arctic or Antarctic",
    "the story of a famous song",
    "queueing and waiting in different cultures",
    "a vet's most unusual patient",
    "how the calendar was invented",
    "a dancer's audition",
    "the tradition of birthday cakes",
    "a cyclist's long-distance ride",
    "how soap was first made",
    "a librarian's favourite book",
    "the history of a castle",
    "a comedian's worst gig",
    "life on board a spaceship",
    "the invention of the telephone",
    "a surprise visit from a relative",
    "coral reefs and marine life",
    "the story of a famous photograph",
    "silence in meditation and mindfulness",
    "an architect's dream project",
    "how fireworks were invented",
    "a farmer's harvest day",
    "the tradition of shaking hands",
    "a climber's near miss",
    "how ice cream spread around the world",
    "a nurse's night shift",
    "the history of a theatre",
    "a writer's block and how they overcame it",
    "life in a monastery or convent",
    "the invention of the camera",
    "a surprise proposal",
    "bees and pollination",
    "the story behind a monument",
    "laughter and humour across cultures",
    "an astronaut's training",
    "how the weekend was created",
    "a fisherman's biggest catch",
    "the tradition of toasting",
    "a surfer's perfect wave",
    "how paper was first made",
    "a bus driver's route",
    "the history of a university",
    "a musician's worst performance",
    "life in a tent or caravan",
    "the invention of the umbrella",
    "a surprise inheritance",
    "owls and other night birds",
    "the story of a famous statue",
    "gestures and body language worldwide",
    "a diver's discovery",
    "how the alphabet was formed",
    "a barber's or hairdresser's tale",
    "the tradition of wedding rings",
    "a skier's avalanche escape",
    "how tea reached Europe",
    "a taxi driver's passenger",
    "the history of a stadium",
    "a painter's favourite light",
    "life in a yurt or igloo",
    "the invention of the wheel",
    "a surprise reunion at an airport",
    "bats and echolocation",
    "the story of a famous bridge",
    "punctuality in different countries",
    "a sailor's storm at sea",
    "how the first map was drawn",
    "a florist's busiest day",
    "the tradition of blowing out candles",
    "a mountaineer's summit",
    "how spices changed history",
    "a train conductor's story",
    "the history of a library",
    "a sculptor's block of stone",
    "life in a submarine",
    "the invention of the mirror",
    "a surprise letter from the past",
    "ants and colony behaviour",
    "the story of a famous tower",
    "siesta and rest around the world",
    "a pilot's emergency landing",
    "how the first book was printed",
    "a jeweller's most valuable piece",
    "the tradition of exchanging gifts",
    "a sailor's round-the-world trip",
    "how sugar spread across the world",
    "a busker's best day",
    "the history of a hospital",
    "a potter's kiln disaster",
    "life in a cave or underground",
    "the invention of the compass",
    "a surprise guest at a wedding",
    "dolphins and communication",
    "the story of a famous fountain",
    "hospitality in different cultures",
    "a cyclist's accident and recovery",
    "how the first clock was made",
    "a tailor's perfect suit",
    "the tradition of naming ships",
    "a kayaker's river journey",
    "how tomatoes came to Europe",
    "a street cleaner's morning",
    "the history of a prison",
    "a glassblower's technique",
    "life in a tree",
    "the invention of the lock",
    "a surprise discovery in an attic",
    "wolves and pack behaviour",
    "the story of a famous square",
    "table manners across cultures",
    "a balloonist's flight",
    "how the first lens was made",
    "a blacksmith's forge",
    "the tradition of midnight on New Year",
    "a rower's race",
    "how potatoes changed diets",
    "a night watchman's rounds",
    "the history of a cemetery",
    "a weaver's pattern",
    "life on a desert island",
    "the invention of the needle",
    "a surprise message in a bottle",
    "elephants and memory",
    "the story of a famous gate",
    "greetings around the world",
]

PART3_TOPICS = [
    "a famous explorer or journey",
    "underwater life and the ocean",
    "a local festival or tradition",
    "migration of birds or animals",
    "street art and urban culture",
    "how coffee or tea became popular",
    "a lost and found object",
    "the history of a bridge or building",
    "volunteering in a community project",
    "learning to cook a family recipe",
    "a day in the life of a lighthouse keeper",
    "the origin of a superstition",
    "a musician's first concert",
    "repairing an old vehicle or machine",
    "a scientific experiment at school",
    "moving to a new country",
    "a surprise party or celebration",
    "wildlife in cities",
    "an unusual hobby or collection",
    "a long-distance friendship",
    "the discovery of a hidden garden",
    "a sports team's comeback",
    "how a word entered the language",
    "a journey by boat or train",
    "a chef's visit to a market",
    "the first day at a new job",
    "a mystery or detective story",
    "climate and weather in a region",
    "a museum or gallery visit",
    "learning to ride a bike or drive",
    "a famous invention and its impact",
    "life in a remote village",
    "a pet that changed someone's life",
    "the story behind a painting or sculpture",
    "a camping or hiking adventure",
    "how newspapers were first delivered",
    "a talent show or competition",
    "the history of a sport",
    "a rescue or act of bravery",
    "food from different cultures",
    "a photographer's favourite subject",
    "ancient customs that still exist",
    "noise and silence in modern life",
    "a journey to the mountains",
    "how a town got its name",
    "a surprise encounter with a celebrity",
    "the importance of sleep",
    "a craft or skill passed down generations",
    "a shipwreck or lost treasure",
    "the life of a street performer",
    "how people celebrated before the internet",
    "a doctor or nurse's memorable day",
    "the history of a park or square",
    "a misunderstanding that led to friendship",
    "extreme weather or natural event",
    "a book that changed someone's view",
    "life on a farm or in the countryside",
    "the first aeroplane flight",
    "a teacher who made a difference",
    "the story of a famous landmark",
    "nocturnal animals and night life",
    "a family business that grew",
    "how music affects mood",
    "a journey through a desert",
    "the tradition of sending postcards",
    "a scientist's breakthrough",
    "sharing a flat or house with others",
    "the history of a type of dance",
    "a film that became a classic",
    "living without technology for a week",
    "a firefighter's or paramedic's story",
    "how languages borrow words",
    "a boat race or sailing event",
    "the meaning of dreams",
    "a comedian's first performance",
    "life in a treehouse or unusual home",
    "the invention of the bicycle",
    "a reunion after many years",
    "endangered species and conservation",
    "a journalist's most memorable interview",
    "the origin of a holiday",
    "learning a new language abroad",
    "a circus or carnival",
    "the story of a famous painting",
    "noise pollution in cities",
    "a pilot's first solo flight",
    "how chocolate is made",
    "a neighbour who became a friend",
    "the history of a river or canal",
    "a magician's secret",
    "life without electricity",
    "the first heart transplant",
    "a gardener's favourite season",
    "the tradition of afternoon tea",
    "a runner's first marathon",
    "how cartoons are made",
    "a sailor's voyage",
    "the discovery of a new species",
    "a baker's early morning",
    "the history of the postal service",
    "a surprise gift or gesture",
    "life in the Arctic or Antarctic",
    "the story of a famous song",
    "queueing and waiting in different cultures",
    "a vet's most unusual patient",
    "how the calendar was invented",
    "a dancer's audition",
    "the tradition of birthday cakes",
    "a cyclist's long-distance ride",
    "how soap was first made",
    "a librarian's favourite book",
    "the history of a castle",
    "a comedian's worst gig",
    "life on board a spaceship",
    "the invention of the telephone",
    "a surprise visit from a relative",
    "coral reefs and marine life",
    "the story of a famous photograph",
    "silence in meditation and mindfulness",
    "an architect's dream project",
    "how fireworks were invented",
    "a farmer's harvest day",
    "the tradition of shaking hands",
    "a climber's near miss",
    "how ice cream spread around the world",
    "a nurse's night shift",
    "the history of a theatre",
    "a writer's block and how they overcame it",
    "life in a monastery or convent",
    "the invention of the camera",
    "a surprise proposal",
    "bees and pollination",
    "the story behind a monument",
    "laughter and humour across cultures",
    "an astronaut's training",
    "how the weekend was created",
    "a fisherman's biggest catch",
    "the tradition of toasting",
    "a surfer's perfect wave",
    "how paper was first made",
    "a bus driver's route",
    "the history of a university",
    "a musician's worst performance",
    "life in a tent or caravan",
    "the invention of the umbrella",
    "a surprise inheritance",
    "owls and other night birds",
    "the story of a famous statue",
    "gestures and body language worldwide",
    "a diver's discovery",
    "how the alphabet was formed",
    "a barber's or hairdresser's tale",
    "the tradition of wedding rings",
    "a skier's avalanche escape",
    "how tea reached Europe",
    "a taxi driver's passenger",
    "the history of a stadium",
    "a painter's favourite light",
    "life in a yurt or igloo",
    "the invention of the wheel",
    "a surprise reunion at an airport",
    "bats and echolocation",
    "the story of a famous bridge",
    "punctuality in different countries",
    "a sailor's storm at sea",
    "how the first map was drawn",
    "a florist's busiest day",
    "the tradition of blowing out candles",
    "a mountaineer's summit",
    "how spices changed history",
    "a train conductor's story",
    "the history of a library",
    "a sculptor's block of stone",
    "life in a submarine",
    "the invention of the mirror",
    "a surprise letter from the past",
    "ants and colony behaviour",
    "the story of a famous tower",
    "siesta and rest around the world",
    "a pilot's emergency landing",
    "how the first book was printed",
    "a jeweller's most valuable piece",
    "the tradition of exchanging gifts",
    "a sailor's round-the-world trip",
    "how sugar spread across the world",
    "a busker's best day",
    "the history of a hospital",
    "a potter's kiln disaster",
    "life in a cave or underground",
    "the invention of the compass",
    "a surprise guest at a wedding",
    "dolphins and communication",
    "the story of a famous fountain",
    "hospitality in different cultures",
    "a cyclist's accident and recovery",
    "how the first clock was made",
    "a tailor's perfect suit",
    "the tradition of naming ships",
    "a kayaker's river journey",
    "how tomatoes came to Europe",
    "a street cleaner's morning",
    "the history of a prison",
    "a glassblower's technique",
    "life in a tree",
    "the invention of the lock",
    "a surprise discovery in an attic",
    "wolves and pack behaviour",
    "the story of a famous square",
    "table manners across cultures",
    "a balloonist's flight",
    "how the first lens was made",
    "a blacksmith's forge",
    "the tradition of midnight on New Year",
    "a rower's race",
    "how potatoes changed diets",
    "a night watchman's rounds",
    "the history of a cemetery",
    "a weaver's pattern",
    "life on a desert island",
    "the invention of the needle",
    "a surprise message in a bottle",
    "elephants and memory",
    "the story of a famous gate",
    "greetings around the world",
]
